--유저 ok
CREATE TABLE USER_INFO (
	ID	VARCHAR2(20)	NOT NULL,
	PW	VARCHAR2(20)	NOT NULL,
	NAME VARCHAR2(20)	NOT NULL,
	TEL	VARCHAR2(20)	NOT NULL,
	ADDR VARCHAR2(200)	NULL,
	B_NAME VARCHAR2(100)	NULL,
	GEN	VARCHAR2(10)	NULL,
	BIR	VARCHAR2(20)	NULL,
	CODE NUMBER(3)	NOT NULL
);
ALTER TABLE USER_INFO ADD CONSTRAINT PK_USER_INFO PRIMARY KEY (ID);

--소화기 정보 PRIMARY KEY 2개가 정상적으로 선언 되었는지??
CREATE TABLE FRXT_INFO (
	F_NICK	VARCHAR2(20) NOT NULL,
	NFC_NUM	NUMBER(10) NOT NULL,
	NFC_PRO	DATE NOT NULL,
	USE_DT	DATE NOT NULL,
	NFC_REGI DATE NOT NULL,
	F_FLR NUMBER(10) NOT NULL,
	F_LOC VARCHAR2(20) NOT NULL
);
-- 기본키 생성 된건지??
ALTER TABLE FRXT_INFO ADD CONSTRAINT PK_FRXT_INFO PRIMARY KEY (
	F_NICK,NFC_NUM
);

CREATE sequence NFC_NUM
start with 1
increment by 1;

drop table FRXT_INFO;
drop sequence NFC_NUM;

--소화기 알림 --> FRXT_INFO에서 NFC_NUM이 정상적으로 외래키로참조가 안됨
CREATE TABLE FRXT_ALR (
	ALR_NUM	NUMBER(6)	NOT NULL,
	NFC_NUM	NUMBER(6)	NOT NULL,
	ID VARCHAR2(20)	NOT NULL,
	ALR_DATE DATE	NOT NULL,
	BLD_DWG	VARCHAR2(50)	NOT NULL,
	ALR_FLR	NUMBER(10)	NOT NULL
);
ALTER TABLE FRXT_ALR ADD CONSTRAINT PK_FRXT_ALR PRIMARY KEY (
	ALR_NUM
);
ALTER TABLE FRXT_ALR ADD CONSTRAINT FK_USER_INFO_TO_FRXT_ALR_1 FOREIGN KEY (
	ID
)
REFERENCES USER_INFO (
	ID
);
-- 외래키 생성 안됨
ALTER TABLE FRXT_ALR ADD CONSTRAINT FK_FRXT_INFO_TO_FRXT_ALR_1 FOREIGN KEY (NFC_NUM)
REFERENCES FRXT_INFO (NFC_NUM);

drop table FRXT_ALR;

--소방 안전 정보 ok
CREATE TABLE FRF_INF (
	FRF_NUM	NUMBER(20)	NOT NULL,
	ID	VARCHAR2(20)	NOT NULL,
	FRF_TLT	VARCHAR2(20)	NOT NULL,
	FRF_CNT	VARCHAR2(20)	NOT NULL,
	FRF_DT	DATE	NOT NULL,
	FRF_IMG	VARCHAR2(20)	NULL
);
ALTER TABLE FRF_INF ADD CONSTRAINT PK_FRF_INF PRIMARY KEY (
	FRF_NUM
);
ALTER TABLE FRF_INF ADD CONSTRAINT FK_USER_INFO_TO_FRF_INF_1 FOREIGN KEY (
	ID
)
REFERENCES USER_INFO (
	ID
);

-- 소화기 수거
CREATE TABLE FRXT_CLC (
	CLC_NO	VARCHAR2(20)	NOT NULL,
	ID	VARCHAR2(20)	NOT NULL,
	NFC_NUM	NUMBER(6)	NOT NULL,
	CLC_DT	DATE	NOT NULL,
	CLC_DSP VARCHAR2(50)	NOT NULL,
	CLC_CLST	VARCHAR2(200)	NOT NULL
);
ALTER TABLE FRXT_CLC ADD CONSTRAINT PK_FRXT_CLC PRIMARY KEY (
	CLC_NO
);
ALTER TABLE FRXT_CLC ADD CONSTRAINT FK_USER_INFO_TO_FRXT_CLC_1 FOREIGN KEY (
	ID
)
REFERENCES USER_INFO (
	ID
);
-- 외래키 생성 안됨
ALTER TABLE FRXT_CLC ADD CONSTRAINT FK_FRXT_INFO_TO_FRXT_CLC_1 FOREIGN KEY (
	NFC_NUM
)
REFERENCES FRXT_INFO (
	NFC_NUM
);
